server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto redirige cualquier ruta al index.html (Vital para Angular)
        try_files $uri $uri/ /index.html;
    }

    # Error 500 para páginas de error personalizadas si quisieras
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}